#!/usr/bin/env bash
# 
# Super simple OneDrive search; assuming a listing was created similar to:
#    cd $ONEDRIVE && ll -R > LIST.OneDrive.ll-R.20200815-1322.txt
#

search=$1
type=search

if [[ -f $search ]]; then
	type=file
elif [[ -d $search ]]; then
	type=directory
else
	type=search
fi

echo "OneDriveSearch: [$search] Type: [$type]"

if [[ $type == 'directory' ]]; then
	for f in "$search"/*
	do
		fb=`basename "$f"`
			
		if [[ $fb != '*' && $fb != 'Thumbs.db' && $fb != 'desktop.ini' && $fb != 'ZbThumbnail.info' && $fb != 'Picasa.ini' ]]; then
			one "$fb" || echo "!!!!!!!!! Unable to find: $f"
		fi
	done
else
	# NOTE: Still have issues with single-quotes in filenames
	# They are being escaped and the egrep call doesn't like that...
	escaped=`printf "%q" "${search}"`
	egrep -i "(^\.|${escaped})" $ONEDRIVE/LIST.OneDrive.*.txt | grep -i -B 1 "$search"
fi
