#!/usr/bin/env bash
# 
# For simple OneDrive search; creates a list of all files and paths
#
# Assumes $ONEDRIVE is configured and pointing to the user's OneDrive root folder

STAMP=`date +"%Y%m%d-%H%M"`
cd $ONEDRIVE
# Rename any existing LISTs to .old
for f in LIST.OneDrive.*.txt; do mv $f `basename $f .txt`.old; done;
# Creating new LIST file
ls -RalF > LIST.OneDrive.ll-R.$STAMP.txt

