#!/usr/bin/env bash

# Script based on comment from: Bertrand Martel at https://stackoverflow.com/questions/46801374/create-a-note-in-privnote-com-using-http-requests

password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c9)
message=$*
data=$(echo "$message" | openssl enc -e -aes-256-cbc -k $password -a -md md5)

note_link=$(curl -s 'https://privnote.com/' \
    -H 'X-Requested-With: XMLHttpRequest' \
    --data-urlencode "data=$data" \
    --data "has_manual_pass=false&duration_hours=0&dont_ask=false&data_type=T&notify_email=&notify_ref=" \
    | jq -r --arg arg $password '.note_link + "#" + $arg')

echo "$note_link"
