#!/usr/bin/env bash

# CD's into each subdirectory of CWD and runs a 'git pull'

for repo in * ;
do
	# Skip non-directories
	if [[ ! -d $repo ]]; then
		continue;
	fi

	# Skip non-git directories
	if [[ ! -d $repo/.git ]]; then
		continue;
	fi

	echo ; echo ; echo ;
	echo "REPO: ${repo}"

	if [[ $repo ]]; then
		cd $repo
		# TODO: show (optionally?) only the most relevant information:
		# (Not yet working)
		# git pull 2>&1 | egrep "^(REPO|error|fatal|    )" 
		git pull 
		cd ..
	fi
done

