#!/usr/bin/env bash

# In the case of WSL2 failing the Linux-to-Windows path translation
#   with an error such as:
#      
#     kevin@local:~/$ explorer.exe .
#     <3>init: (9044) ERROR: UtilConnectToInteropServer:300: connect failed 2
#
# From: https://github.com/microsoft/WSL/issues/5065
# You must have this function in your .bashrc script:
#
# fix_wsl2_interop() {
#     for i in $(pstree -np -s $$ | grep -o -E '[0-9]+'); do
#         if [[ -e "/run/WSL/${i}_interop" ]]; then
#             export WSL_INTEROP=/run/WSL/${i}_interop
#         fi
#     done
# }
# 
# This doesn't work as a script, because the script runs in isolation

# This won't really work/help...
#fix_wsl2_interop

echo "Run: fix_wsl2_interop"
